export * from './home'
export * from './upcomingMovies'
export * from './movieDetails'
export * from './login'
export * from './searchResults'
export * from './fullCastCrew'
export * from './profile'
export * from './reviews'