name: Movies tracker CI/CD

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Check if unit tests passed
        run: |
          if [ $? -eq 0 ]; then
            echo "All unit tests passed. Generating coverage report..."
            npm run coverage 
          else
            echo "Unit tests failed. Skipping coverage report generation."
          fi

      - name: Deploy coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          BRANCH: coverage-report
          FOLDER: coverage
